function displayFields(form, customHTML) {
    var activity = getValue('WKNumState');
    customHTML.append("<script type='text/javascript'>");
    customHTML.append("let MODE = '" + form.getFormMode() + "';");
    customHTML.append("let ATIVIDADE = " + getValue("WKNumState") + ";");
	customHTML.append("let NUM_PROCESS = '" + form.getFormMode() + "';");
    customHTML.append("</script>");
    
      if (activity == 16) {
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="aprov_DirAdj"]\').css(\'display\', \'none\');var closers = $(\'*[name="aprov_DirAdj"]\').closest(\'.form-field\').find(\'input, textarea, select\');var hideDiv = true;$.each(closers, function(i, close) {if (close.style.display != \'none\' && close.type != \'hidden\') {hideDiv = false;}});if (hideDiv == true) {$(\'*[name="aprov_DirAdj"]\').closest(\'.form-field\').css(\'display\', \'none\');}');
          customHTML.append('</script>');
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="aprov_DirAdj"]\').closest("li").hide()');
          customHTML.append('</script>');
      }
      if (activity == 5 || activity == 0) {
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="Conside_solicit"]\').css(\'display\', \'none\');var closers = $(\'*[name="Conside_solicit"]\').closest(\'.form-field\').find(\'input, textarea, select\');var hideDiv = true;$.each(closers, function(i, close) {if (close.style.display != \'none\' && close.type != \'hidden\') {hideDiv = false;}});if (hideDiv == true) {$(\'*[name="Conside_solicit"]\').closest(\'.form-field\').css(\'display\', \'none\');}');
          customHTML.append('</script>');
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="Conside_solicit"]\').closest("li").hide()');
          customHTML.append('</script>');
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="Ajustes_Di_adj"]\').css(\'display\', \'none\');var closers = $(\'*[name="Ajustes_Di_adj"]\').closest(\'.form-field\').find(\'input, textarea, select\');var hideDiv = true;$.each(closers, function(i, close) {if (close.style.display != \'none\' && close.type != \'hidden\') {hideDiv = false;}});if (hideDiv == true) {$(\'*[name="Ajustes_Di_adj"]\').closest(\'.form-field\').css(\'display\', \'none\');}');
          customHTML.append('</script>');
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="Ajustes_Di_adj"]\').closest("li").hide()');
          customHTML.append('</script>');
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="Ajustes_P_E"]\').css(\'display\', \'none\');var closers = $(\'*[name="Ajustes_P_E"]\').closest(\'.form-field\').find(\'input, textarea, select\');var hideDiv = true;$.each(closers, function(i, close) {if (close.style.display != \'none\' && close.type != \'hidden\') {hideDiv = false;}});if (hideDiv == true) {$(\'*[name="Ajustes_P_E"]\').closest(\'.form-field\').css(\'display\', \'none\');}');
          customHTML.append('</script>');
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="Ajustes_P_E"]\').closest("li").hide()');
          customHTML.append('</script>');
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="Ajustes_R_P"]\').css(\'display\', \'none\');var closers = $(\'*[name="Ajustes_R_P"]\').closest(\'.form-field\').find(\'input, textarea, select\');var hideDiv = true;$.each(closers, function(i, close) {if (close.style.display != \'none\' && close.type != \'hidden\') {hideDiv = false;}});if (hideDiv == true) {$(\'*[name="Ajustes_R_P"]\').closest(\'.form-field\').css(\'display\', \'none\');}');
          customHTML.append('</script>');
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="Ajustes_R_P"]\').closest("li").hide()');
          customHTML.append('</script>');
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="aprov_DirAdj"]\').css(\'display\', \'none\');var closers = $(\'*[name="aprov_DirAdj"]\').closest(\'.form-field\').find(\'input, textarea, select\');var hideDiv = true;$.each(closers, function(i, close) {if (close.style.display != \'none\' && close.type != \'hidden\') {hideDiv = false;}});if (hideDiv == true) {$(\'*[name="aprov_DirAdj"]\').closest(\'.form-field\').css(\'display\', \'none\');}');
          customHTML.append('</script>');
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="aprov_DirAdj"]\').closest("li").hide()');
          customHTML.append('</script>');
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="Valid_P_E"]\').css(\'display\', \'none\');var closers = $(\'*[name="Valid_P_E"]\').closest(\'.form-field\').find(\'input, textarea, select\');var hideDiv = true;$.each(closers, function(i, close) {if (close.style.display != \'none\' && close.type != \'hidden\') {hideDiv = false;}});if (hideDiv == true) {$(\'*[name="Valid_P_E"]\').closest(\'.form-field\').css(\'display\', \'none\');}');
          customHTML.append('</script>');
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="Valid_P_E"]\').closest("li").hide()');
          customHTML.append('</script>');
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="Aprov_RP"]\').css(\'display\', \'none\');var closers = $(\'*[name="Aprov_RP"]\').closest(\'.form-field\').find(\'input, textarea, select\');var hideDiv = true;$.each(closers, function(i, close) {if (close.style.display != \'none\' && close.type != \'hidden\') {hideDiv = false;}});if (hideDiv == true) {$(\'*[name="Aprov_RP"]\').closest(\'.form-field\').css(\'display\', \'none\');}');
          customHTML.append('</script>');
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="Aprov_RP"]\').closest("li").hide()');
          customHTML.append('</script>');
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="Aprov_Dir_Exec"]\').css(\'display\', \'none\');var closers = $(\'*[name="Aprov_Dir_Exec"]\').closest(\'.form-field\').find(\'input, textarea, select\');var hideDiv = true;$.each(closers, function(i, close) {if (close.style.display != \'none\' && close.type != \'hidden\') {hideDiv = false;}});if (hideDiv == true) {$(\'*[name="Aprov_Dir_Exec"]\').closest(\'.form-field\').css(\'display\', \'none\');}');
          customHTML.append('</script>');
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="Aprov_Dir_Exec"]\').closest("li").hide()');
          customHTML.append('</script>');
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="Ajus_Dir_Execu"]\').css(\'display\', \'none\');var closers = $(\'*[name="Ajus_Dir_Execu"]\').closest(\'.form-field\').find(\'input, textarea, select\');var hideDiv = true;$.each(closers, function(i, close) {if (close.style.display != \'none\' && close.type != \'hidden\') {hideDiv = false;}});if (hideDiv == true) {$(\'*[name="Ajus_Dir_Execu"]\').closest(\'.form-field\').css(\'display\', \'none\');}');
          customHTML.append('</script>');
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="Ajus_Dir_Execu"]\').closest("li").hide()');
          customHTML.append('</script>');
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="Conside_solicit"]\').css(\'display\', \'none\');var closers = $(\'*[name="Conside_solicit"]\').closest(\'.form-field\').find(\'input, textarea, select\');var hideDiv = true;$.each(closers, function(i, close) {if (close.style.display != \'none\' && close.type != \'hidden\') {hideDiv = false;}});if (hideDiv == true) {$(\'*[name="Conside_solicit"]\').closest(\'.form-field\').css(\'display\', \'none\');}');
          customHTML.append('</script>');
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="Conside_solicit"]\').closest("li").hide()');
          customHTML.append('</script>');
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="Aprov_R_OE"]\').css(\'display\', \'none\');var closers = $(\'*[name="Aprov_R_OE"]\').closest(\'.form-field\').find(\'input, textarea, select\');var hideDiv = true;$.each(closers, function(i, close) {if (close.style.display != \'none\' && close.type != \'hidden\') {hideDiv = false;}});if (hideDiv == true) {$(\'*[name="Aprov_R_OE"]\').closest(\'.form-field\').css(\'display\', \'none\');}');
          customHTML.append('</script>');
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="Aprov_R_OE"]\').closest("li").hide()');
          customHTML.append('</script>');
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="Ajustes_R_OE"]\').css(\'display\', \'none\');var closers = $(\'*[name="Ajustes_R_OE"]\').closest(\'.form-field\').find(\'input, textarea, select\');var hideDiv = true;$.each(closers, function(i, close) {if (close.style.display != \'none\' && close.type != \'hidden\') {hideDiv = false;}});if (hideDiv == true) {$(\'*[name="Ajustes_R_OE"]\').closest(\'.form-field\').css(\'display\', \'none\');}');
          customHTML.append('</script>');
          customHTML.append('<script>');
          customHTML.append('$(\'*[name="Ajustes_R_OE"]\').closest("li").hide()');
          customHTML.append('</script>');
      }
}